
[build]
functions = "api/"
ignore = "git diff --quiet HEAD^ HEAD ../../"
publish = "public/"

[[redirects]]
# Sitemap
force = true
from = "/sitemap.xml"
headers = {Content-Type = "xml"}
status = 200
to = "/static/sitemap.xml"

[[redirects]]
# SSR and SPA
from = "/*"
status = 200
to = "/.netlify/functions/ssr"

# SPA only
# from = "/*"
# to = "/__app.html"
# status = 200
