
[build]
functions = "api/"
ignore = "git diff --quiet HEAD^ HEAD ../../"
publish = "public/"

[[redirects]]
# SSR and SPA
from = "/*"
status = 200
to = "/.netlify/functions/ssr"

# As suggested at https://github.com/netlify-labs/netlify-plugin-sitemap
[[plugins]]
package = "plugin-sitemap"

[plugins.inputs]
changeFreq = "monthly"
priority = 0.5

# SPA only
# from = "/*"
# to = "/__app.html"
# status = 200
